//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Data.EntityClient;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Linq;
using System.Runtime.Serialization;
using System.Xml.Serialization;

[assembly: EdmSchemaAttribute()]
#region Metadatos de relaciones en EDM

[assembly: EdmRelationshipAttribute("RUTASModel", "FK__Ventas__IdClient__398D8EEE", "Clientes", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(ConsoleApp7.Clientes), "Ventas", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(ConsoleApp7.Ventas), true)]

#endregion

namespace ConsoleApp7
{
    #region Contextos
    
    /// <summary>
    /// No hay documentación de metadatos disponible.
    /// </summary>
    public partial class RUTASTURISTICAS : ObjectContext
    {
        #region Constructores
    
        /// <summary>
        /// Inicializa un nuevo objeto RUTASTURISTICAS usando la cadena de conexión encontrada en la sección 'RUTASTURISTICAS' del archivo de configuración de la aplicación.
        /// </summary>
        public RUTASTURISTICAS() : base("name=RUTASTURISTICAS", "RUTASTURISTICAS")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Inicializar un nuevo objeto RUTASTURISTICAS.
        /// </summary>
        public RUTASTURISTICAS(string connectionString) : base(connectionString, "RUTASTURISTICAS")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Inicializar un nuevo objeto RUTASTURISTICAS.
        /// </summary>
        public RUTASTURISTICAS(EntityConnection connection) : base(connection, "RUTASTURISTICAS")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Métodos parciales
    
        partial void OnContextCreated();
    
        #endregion
    
        #region Propiedades de ObjectSet
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        public ObjectSet<Clientes> Clientes
        {
            get
            {
                if ((_Clientes == null))
                {
                    _Clientes = base.CreateObjectSet<Clientes>("Clientes");
                }
                return _Clientes;
            }
        }
        private ObjectSet<Clientes> _Clientes;
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        public ObjectSet<Rutas> Rutas
        {
            get
            {
                if ((_Rutas == null))
                {
                    _Rutas = base.CreateObjectSet<Rutas>("Rutas");
                }
                return _Rutas;
            }
        }
        private ObjectSet<Rutas> _Rutas;
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        public ObjectSet<Ventas> Ventas
        {
            get
            {
                if ((_Ventas == null))
                {
                    _Ventas = base.CreateObjectSet<Ventas>("Ventas");
                }
                return _Ventas;
            }
        }
        private ObjectSet<Ventas> _Ventas;

        #endregion

        #region Métodos AddTo
    
        /// <summary>
        /// Método desusado para agregar un nuevo objeto al EntitySet Clientes. Considere la posibilidad de usar el método .Add de la propiedad ObjectSet&lt;T&gt; asociada.
        /// </summary>
        public void AddToClientes(Clientes clientes)
        {
            base.AddObject("Clientes", clientes);
        }
    
        /// <summary>
        /// Método desusado para agregar un nuevo objeto al EntitySet Rutas. Considere la posibilidad de usar el método .Add de la propiedad ObjectSet&lt;T&gt; asociada.
        /// </summary>
        public void AddToRutas(Rutas rutas)
        {
            base.AddObject("Rutas", rutas);
        }
    
        /// <summary>
        /// Método desusado para agregar un nuevo objeto al EntitySet Ventas. Considere la posibilidad de usar el método .Add de la propiedad ObjectSet&lt;T&gt; asociada.
        /// </summary>
        public void AddToVentas(Ventas ventas)
        {
            base.AddObject("Ventas", ventas);
        }

        #endregion

    }

    #endregion

    #region Entidades
    
    /// <summary>
    /// No hay documentación de metadatos disponible.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="RUTASModel", Name="Clientes")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Clientes : EntityObject
    {
        #region Método de generador
    
        /// <summary>
        /// Crear un nuevo objeto Clientes.
        /// </summary>
        /// <param name="idCliente">Valor inicial de la propiedad IdCliente.</param>
        public static Clientes CreateClientes(global::System.Int32 idCliente)
        {
            Clientes clientes = new Clientes();
            clientes.IdCliente = idCliente;
            return clientes;
        }

        #endregion

        #region Propiedades simples
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 IdCliente
        {
            get
            {
                return _IdCliente;
            }
            set
            {
                if (_IdCliente != value)
                {
                    OnIdClienteChanging(value);
                    ReportPropertyChanging("IdCliente");
                    _IdCliente = StructuralObject.SetValidValue(value, "IdCliente");
                    ReportPropertyChanged("IdCliente");
                    OnIdClienteChanged();
                }
            }
        }
        private global::System.Int32 _IdCliente;
        partial void OnIdClienteChanging(global::System.Int32 value);
        partial void OnIdClienteChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Nombre
        {
            get
            {
                return _Nombre;
            }
            set
            {
                OnNombreChanging(value);
                ReportPropertyChanging("Nombre");
                _Nombre = StructuralObject.SetValidValue(value, true, "Nombre");
                ReportPropertyChanged("Nombre");
                OnNombreChanged();
            }
        }
        private global::System.String _Nombre;
        partial void OnNombreChanging(global::System.String value);
        partial void OnNombreChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String TipoCliente
        {
            get
            {
                return _TipoCliente;
            }
            set
            {
                OnTipoClienteChanging(value);
                ReportPropertyChanging("TipoCliente");
                _TipoCliente = StructuralObject.SetValidValue(value, true, "TipoCliente");
                ReportPropertyChanged("TipoCliente");
                OnTipoClienteChanged();
            }
        }
        private global::System.String _TipoCliente;
        partial void OnTipoClienteChanging(global::System.String value);
        partial void OnTipoClienteChanged();

        #endregion

        #region Propiedades de navegación
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("RUTASModel", "FK__Ventas__IdClient__398D8EEE", "Ventas")]
        public EntityCollection<Ventas> Ventas
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Ventas>("RUTASModel.FK__Ventas__IdClient__398D8EEE", "Ventas");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Ventas>("RUTASModel.FK__Ventas__IdClient__398D8EEE", "Ventas", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No hay documentación de metadatos disponible.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="RUTASModel", Name="Rutas")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Rutas : EntityObject
    {
        #region Método de generador
    
        /// <summary>
        /// Crear un nuevo objeto Rutas.
        /// </summary>
        /// <param name="idRuta">Valor inicial de la propiedad IdRuta.</param>
        public static Rutas CreateRutas(global::System.Int32 idRuta)
        {
            Rutas rutas = new Rutas();
            rutas.IdRuta = idRuta;
            return rutas;
        }

        #endregion

        #region Propiedades simples
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 IdRuta
        {
            get
            {
                return _IdRuta;
            }
            set
            {
                if (_IdRuta != value)
                {
                    OnIdRutaChanging(value);
                    ReportPropertyChanging("IdRuta");
                    _IdRuta = StructuralObject.SetValidValue(value, "IdRuta");
                    ReportPropertyChanged("IdRuta");
                    OnIdRutaChanged();
                }
            }
        }
        private global::System.Int32 _IdRuta;
        partial void OnIdRutaChanging(global::System.Int32 value);
        partial void OnIdRutaChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String NombreRuta
        {
            get
            {
                return _NombreRuta;
            }
            set
            {
                OnNombreRutaChanging(value);
                ReportPropertyChanging("NombreRuta");
                _NombreRuta = StructuralObject.SetValidValue(value, true, "NombreRuta");
                ReportPropertyChanged("NombreRuta");
                OnNombreRutaChanged();
            }
        }
        private global::System.String _NombreRuta;
        partial void OnNombreRutaChanging(global::System.String value);
        partial void OnNombreRutaChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Decimal> Precio
        {
            get
            {
                return _Precio;
            }
            set
            {
                OnPrecioChanging(value);
                ReportPropertyChanging("Precio");
                _Precio = StructuralObject.SetValidValue(value, "Precio");
                ReportPropertyChanged("Precio");
                OnPrecioChanged();
            }
        }
        private Nullable<global::System.Decimal> _Precio;
        partial void OnPrecioChanging(Nullable<global::System.Decimal> value);
        partial void OnPrecioChanged();

        #endregion

    }
    
    /// <summary>
    /// No hay documentación de metadatos disponible.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="RUTASModel", Name="Ventas")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Ventas : EntityObject
    {
        #region Método de generador
    
        /// <summary>
        /// Crear un nuevo objeto Ventas.
        /// </summary>
        /// <param name="idVenta">Valor inicial de la propiedad IdVenta.</param>
        public static Ventas CreateVentas(global::System.Int32 idVenta)
        {
            Ventas ventas = new Ventas();
            ventas.IdVenta = idVenta;
            return ventas;
        }

        #endregion

        #region Propiedades simples
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 IdVenta
        {
            get
            {
                return _IdVenta;
            }
            set
            {
                if (_IdVenta != value)
                {
                    OnIdVentaChanging(value);
                    ReportPropertyChanging("IdVenta");
                    _IdVenta = StructuralObject.SetValidValue(value, "IdVenta");
                    ReportPropertyChanged("IdVenta");
                    OnIdVentaChanged();
                }
            }
        }
        private global::System.Int32 _IdVenta;
        partial void OnIdVentaChanging(global::System.Int32 value);
        partial void OnIdVentaChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> IdCliente
        {
            get
            {
                return _IdCliente;
            }
            set
            {
                OnIdClienteChanging(value);
                ReportPropertyChanging("IdCliente");
                _IdCliente = StructuralObject.SetValidValue(value, "IdCliente");
                ReportPropertyChanged("IdCliente");
                OnIdClienteChanged();
            }
        }
        private Nullable<global::System.Int32> _IdCliente;
        partial void OnIdClienteChanging(Nullable<global::System.Int32> value);
        partial void OnIdClienteChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> IdRuta
        {
            get
            {
                return _IdRuta;
            }
            set
            {
                OnIdRutaChanging(value);
                ReportPropertyChanging("IdRuta");
                _IdRuta = StructuralObject.SetValidValue(value, "IdRuta");
                ReportPropertyChanged("IdRuta");
                OnIdRutaChanged();
            }
        }
        private Nullable<global::System.Int32> _IdRuta;
        partial void OnIdRutaChanging(Nullable<global::System.Int32> value);
        partial void OnIdRutaChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> CantidadPersonas
        {
            get
            {
                return _CantidadPersonas;
            }
            set
            {
                OnCantidadPersonasChanging(value);
                ReportPropertyChanging("CantidadPersonas");
                _CantidadPersonas = StructuralObject.SetValidValue(value, "CantidadPersonas");
                ReportPropertyChanged("CantidadPersonas");
                OnCantidadPersonasChanged();
            }
        }
        private Nullable<global::System.Int32> _CantidadPersonas;
        partial void OnCantidadPersonasChanging(Nullable<global::System.Int32> value);
        partial void OnCantidadPersonasChanged();

        #endregion

        #region Propiedades de navegación
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("RUTASModel", "FK__Ventas__IdClient__398D8EEE", "Clientes")]
        public Clientes Clientes
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Clientes>("RUTASModel.FK__Ventas__IdClient__398D8EEE", "Clientes").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Clientes>("RUTASModel.FK__Ventas__IdClient__398D8EEE", "Clientes").Value = value;
            }
        }
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Clientes> ClientesReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Clientes>("RUTASModel.FK__Ventas__IdClient__398D8EEE", "Clientes");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Clientes>("RUTASModel.FK__Ventas__IdClient__398D8EEE", "Clientes", value);
                }
            }
        }

        #endregion

    }

    #endregion

}
